"""
Omnix - Report Tool (Dataset-Agnostic)
Generates both CSV summary and Plotly-powered interactive HTML report.
"""

import json
import os
from typing import Any, Dict

import duckdb
import pandas as pd

from agent.utils import (
    REPORTS_DIR,
    WAREHOUSE_DB_PATH,
    categorize_columns,
    load_schema,
    quote_identifier,
    validate_identifier,
    validate_sql,
)
from user_workspace import get_user_workspace, load_user_schema, save_user_schema


class ReportTool:
    """Tool for generating reports - Dataset agnostic."""

    @staticmethod
    def _get_report_filename(schema: Dict[str, Any]) -> str:
        clean_table = schema.get("table_name", "data_clean")
        base = clean_table.replace("_clean", "")
        return f"{base}_report.csv"

    @staticmethod
    def _get_report_html_filename(schema: Dict[str, Any]) -> str:
        clean_table = schema.get("table_name", "data_clean")
        base = clean_table.replace("_clean", "")
        return f"{base}_report.html"

    @staticmethod
    def _get_report_path(schema: Dict[str, Any], user_id: str | None = None) -> str:
        workspace = get_user_workspace(user_id)
        return os.path.join(workspace["reports_dir"], ReportTool._get_report_filename(schema))

    @staticmethod
    def _get_report_html_path(schema: Dict[str, Any], user_id: str | None = None) -> str:
        workspace = get_user_workspace(user_id)
        return os.path.join(workspace["reports_dir"], ReportTool._get_report_html_filename(schema))

    @staticmethod
    def _build_plotly_html(report_title: str, charts: Dict[str, Any]) -> str:
        payload = json.dumps(charts, default=str)
        safe_title = report_title.replace("<", "&lt;").replace(">", "&gt;")
        return f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"UTF-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
  <title>{safe_title}</title>
  <script src=\"https://cdn.plot.ly/plotly-2.35.2.min.js\"></script>
  <style>
    body {{ font-family: Segoe UI, sans-serif; margin: 20px; background: #0b0f14; color: #f8fafc; }}
    h1 {{ margin: 0 0 6px 0; }}
    p {{ color: #cbd5e1; margin: 0 0 18px 0; }}
    .grid {{ display: grid; grid-template-columns: repeat(2, minmax(300px, 1fr)); gap: 14px; }}
    .card {{ background: #111827; border: 1px solid #1f2937; border-radius: 10px; padding: 10px; }}
    .plot {{ height: 340px; }}
    @media (max-width: 900px) {{ .grid {{ grid-template-columns: 1fr; }} }}
  </style>
</head>
<body>
  <h1>{safe_title}</h1>
  <p>Interactive report generated by Omnix.</p>
  <div class=\"grid\">
    <div class=\"card\"><div id=\"bar\" class=\"plot\"></div></div>
    <div class=\"card\"><div id=\"line\" class=\"plot\"></div></div>
    <div class=\"card\"><div id=\"pie\" class=\"plot\"></div></div>
    <div class=\"card\"><div id=\"hist\" class=\"plot\"></div></div>
    <div class=\"card\" style=\"grid-column: 1 / -1;\"><div id=\"heatmap\" class=\"plot\" style=\"height:420px;\"></div></div>
  </div>
  <script>
    const charts = {payload};
    Plotly.newPlot('bar', [{{ type: 'bar', x: charts.bar.map(x => x.category), y: charts.bar.map(x => x.value) }}], {{ title: 'Bar' }});
    Plotly.newPlot('line', [{{ type: 'scatter', mode: 'lines+markers', x: charts.line.map(x => x.period), y: charts.line.map(x => x.value) }}], {{ title: 'Line Trend' }});
    Plotly.newPlot('pie', [{{ type: 'pie', labels: charts.pie.map(x => x.name), values: charts.pie.map(x => x.value) }}], {{ title: 'Pie' }});
    Plotly.newPlot('hist', [{{ type: 'bar', x: charts.histogram.map(x => x.bucket), y: charts.histogram.map(x => x.count) }}], {{ title: 'Histogram' }});
    const xVals = [...new Set(charts.heatmap.map(x => x.x))];
    const yVals = [...new Set(charts.heatmap.map(x => x.y))];
    const z = yVals.map(y => xVals.map(x => (charts.heatmap.find(h => h.x === x && h.y === y) || {{ value: 0 }}).value));
    Plotly.newPlot('heatmap', [{{ type: 'heatmap', x: xVals, y: yVals, z }}], {{ title: 'Correlation Heatmap' }});
  </script>
</body>
</html>"""

    async def generate(self, schema: Dict[str, Any] = None, user_id: str | None = None) -> str:
        """Generate CSV + interactive HTML report."""
        if schema is None:
            schema = load_user_schema(user_id) or load_schema()

        if not schema or not schema.get("columns"):
            return "Error: No schema loaded. Upload and ingest data first."

        table_name = schema.get("table_name", "data_clean")
        if not validate_identifier(table_name):
            return f"Error: Invalid table name: {table_name!r}"

        workspace = get_user_workspace(user_id)
        warehouse_db = workspace["warehouse_db"]
        if not os.path.exists(warehouse_db):
            warehouse_db = WAREHOUSE_DB_PATH
        if not os.path.exists(warehouse_db):
            return "Error: Warehouse not found. Run pipeline first."

        report_path = self._get_report_path(schema, user_id=user_id)
        report_html_path = self._get_report_html_path(schema, user_id=user_id)
        os.makedirs(os.path.dirname(report_path), exist_ok=True)
        os.makedirs(os.path.dirname(report_html_path), exist_ok=True)

        con = duckdb.connect(warehouse_db)
        quoted_table = quote_identifier(table_name)

        try:
            con.execute(f"SELECT * FROM {quoted_table} LIMIT 1")
        except duckdb.Error:
            con.close()
            return f"Error: Table {table_name} not found. Run transformation first."

        col_cats = categorize_columns(schema.get("columns", {}))
        numeric_cols = col_cats["numeric"]
        category_cols = col_cats["categorical"]

        report_sql = None
        if category_cols and numeric_cols:
            group_col = category_cols[0]
            agg_col = numeric_cols[0]
            quoted_group = quote_identifier(group_col)
            quoted_agg = quote_identifier(agg_col)
            report_sql = f"""
                SELECT
                    {quoted_group},
                    COUNT(*) as record_count,
                    SUM({quoted_agg}) as total_{agg_col},
                    ROUND(AVG({quoted_agg}), 2) as avg_{agg_col},
                    MIN({quoted_agg}) as min_{agg_col},
                    MAX({quoted_agg}) as max_{agg_col}
                FROM {quoted_table}
                GROUP BY {quoted_group}
                ORDER BY total_{agg_col} DESC
            """
        elif category_cols:
            group_col = category_cols[0]
            quoted_group = quote_identifier(group_col)
            report_sql = f"""
                SELECT
                    {quoted_group},
                    COUNT(*) as record_count
                FROM {quoted_table}
                GROUP BY {quoted_group}
                ORDER BY record_count DESC
            """
        elif numeric_cols:
            agg_col = numeric_cols[0]
            quoted_agg = quote_identifier(agg_col)
            report_sql = f"""
                SELECT
                    COUNT(*) as record_count,
                    SUM({quoted_agg}) as total_{agg_col},
                    ROUND(AVG({quoted_agg}), 2) as avg_{agg_col},
                    MIN({quoted_agg}) as min_{agg_col},
                    MAX({quoted_agg}) as max_{agg_col}
                FROM {quoted_table}
            """
        else:
            report_sql = f"SELECT COUNT(*) as record_count FROM {quoted_table}"

        is_safe, reason = validate_sql(report_sql)
        if not is_safe:
            con.close()
            return f"Error: Report SQL validation failed: {reason}"

        try:
            report_df = con.execute(report_sql).fetchdf()
            full_df = con.execute(f"SELECT * FROM {quoted_table}").fetchdf()
            report_df.to_csv(report_path, index=False)
            count = int(len(report_df))
            con.close()
        except duckdb.Error as e:
            con.close()
            return f"Error: Failed to generate report: {e}"

        numeric_df = full_df.select_dtypes(include=["number"])
        numeric = list(numeric_df.columns)
        non_numeric = [c for c in full_df.columns if c not in numeric]

        bar = []
        pie = []
        line = []
        histogram = []
        heatmap = []

        if non_numeric and numeric:
            cat = non_numeric[0]
            num = numeric[0]
            grouped = full_df.groupby(cat, dropna=False)[num].sum().reset_index().sort_values(num, ascending=False).head(12)
            bar = [{"category": str(r[cat]), "value": float(r[num])} for _, r in grouped.iterrows()]
            pie = [{"name": str(r[cat]), "value": float(r[num])} for _, r in grouped.head(8).iterrows()]

        if numeric:
            num = numeric[0]
            hist = pd.cut(full_df[num], bins=12).value_counts(sort=False)
            histogram = [{"bucket": str(k), "count": int(v)} for k, v in hist.items()]
            corr = full_df[numeric].corr().fillna(0)
            for row in corr.index:
                for col in corr.columns:
                    heatmap.append({"x": str(col), "y": str(row), "value": float(round(corr.loc[row, col], 4))})

        for col in full_df.columns:
            parsed = pd.to_datetime(full_df[col], errors="coerce")
            if parsed.notna().mean() > 0.7 and numeric:
                num = numeric[0]
                tmp = full_df.copy()
                tmp[col] = parsed
                trend_df = tmp.dropna(subset=[col])
                if not trend_df.empty:
                    trend_df["_period"] = trend_df[col].dt.to_period("M").astype(str)
                    grouped = trend_df.groupby("_period")[num].sum().reset_index().sort_values("_period").tail(12)
                    line = [{"period": str(r["_period"]), "value": float(r[num])} for _, r in grouped.iterrows()]
                break

        charts = {
            "bar": bar,
            "line": line,
            "pie": pie,
            "histogram": histogram,
            "heatmap": heatmap,
        }

        report_title = f"Omnix Interactive Report - {table_name}"
        html = self._build_plotly_html(report_title, charts)
        with open(report_html_path, "w", encoding="utf-8") as f:
            f.write(html)

        schema["report_file"] = report_path
        schema["report_html_file"] = report_html_path
        save_user_schema(user_id, schema)

        csv_name = self._get_report_filename(schema)
        html_name = self._get_report_html_filename(schema)
        return f"Generated report with {count} rows: {csv_name} and {html_name}"
