version: 2

sources:
  - name: raw
    database: main
    schema: main
    tables:
      - name: student_performance_data_raw
        description: "Raw medical data ingested from source"

models:
  - name: stg_student_performance_data_clean
    description: "Staging model for medical data — cleaned and standardized"
    columns:
      - name: student_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: gender
        description: "gender dimension"
        tests:
          - not_null

  - name: int_medical_aggregated
    description: "Intermediate model with aggregated metrics by gender"
    columns:
      - name: gender
        tests:
          - unique
          - not_null

  - name: mart_medical_analytics
    description: "Final analytics mart combining all transformations"
