"""
DataForge AI - Generated Pipeline
Auto-generated by DataForge Agent
Generated at: 2026-07-24T08:31:23.877806
Operations: ingest, transform, report
Dataset Type: sales
"""

import duckdb
import pandas as pd
from datetime import datetime
import os

class DataPipeline:
    """Auto-generated Data Pipeline for sales dataset"""

    def __init__(self):
        self.base_path = os.path.normpath(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
        self.warehouse_path = os.path.join(self.base_path, "warehouse", "warehouse.duckdb")
        source_file = os.path.normpath("/tmp/dftest/messy_sales.csv")
        if os.path.isabs(source_file):
            self.raw_data_path = source_file
        else:
            self.raw_data_path = os.path.normpath(os.path.join(self.base_path, source_file))
        self.clean_data_path = os.path.join(self.base_path, "data", "clean", "messy_sales_clean.csv")
        self.report_path = os.path.join(self.base_path, "reports", "messy_sales_clean_report.csv")
        self.logs = []

    def log(self, message):
        timestamp = datetime.now().strftime("%H:%M:%S")
        self.logs.append(f"[{timestamp}] {message}")
        print(message)

    def ingest(self):
        """Ingest raw data into DuckDB warehouse"""
        self.log("[Ingest] Reading raw data...")
        
        if not os.path.exists(self.raw_data_path):
            self.log(f"[Ingest] Error: Raw data file not at {self.raw_data_path}")
            return False
        
        df = pd.read_csv(self.raw_data_path)
        self.log(f"[Ingest] Loaded {len(df)} rows")
        
        os.makedirs(os.path.dirname(self.warehouse_path), exist_ok=True)
        
        con = duckdb.connect(self.warehouse_path)
        con.execute("CREATE OR REPLACE TABLE messy_sales_raw AS SELECT * FROM df")
        
        count = con.execute("SELECT COUNT(*) FROM messy_sales_raw").fetchone()[0]
        con.close()
        
        self.log(f"[Ingest] Data ingested to warehouse ({count} rows)")
        return True
    def transform(self):
        """Transform and clean data"""
        self.log("[Transform] Cleaning data...")
        
        con = duckdb.connect(self.warehouse_path)
        
        con.execute("""
            CREATE OR REPLACE TABLE messy_sales_clean AS
            SELECT 
                CAST(customer_id AS INTEGER) as customer_id,
                customer_name,
                city,
                age,
                plan,
                CAST(revenue AS DOUBLE) as revenue,
                TRY_CAST(signup_date AS DATE) as signup_date,
                notes
            FROM messy_sales_raw
            WHERE customer_id IS NOT NULL
        """)
        
        os.makedirs(os.path.dirname(self.clean_data_path), exist_ok=True)
        df = con.execute("SELECT * FROM messy_sales_clean").fetchdf()
        df.to_csv(self.clean_data_path, index=False)
        
        count = len(df)
        con.close()
        
        self.log(f"[Transform] Cleaned {count} rows saved")
        return True
    def generate_report(self):
        """Generate summary report"""
        self.log("[Report] Generating report...")
        
        con = duckdb.connect(self.warehouse_path)
        report_df = con.execute("""
            SELECT 
                city,
                COUNT(*) as record_count,
                SUM(customer_id) as total_customer_id,
                ROUND(AVG(customer_id), 2) as avg_customer_id
            FROM messy_sales_clean
            GROUP BY city
            ORDER BY total_customer_id DESC
        """).fetchdf()
        
        os.makedirs(os.path.dirname(self.report_path), exist_ok=True)
        report_df.to_csv(self.report_path, index=False)
        
        count = len(report_df)
        con.close()
        
        self.log(f"[Report] Generated report with {count} rows")
        return True
    def run(self):
        """Execute full pipeline"""
        start_time = datetime.now()
        self.log("=" * 50)
        self.log("DataForge AI Pipeline Execution")
        self.log(f"Dataset: sales")
        self.log(f"Started: {start_time}")
        self.log("=" * 50)
        
        results = {}
        files = []
        
        
        self.log("Step 1: Ingesting data...")
        results["ingest"] = self.ingest()
        if results["ingest"]:
            files.append("warehouse/warehouse.duckdb") 
        self.log("Step 2: Transforming data...")
        results["transform"] = self.transform()
        if results["transform"]:
            files.append("data/clean/messy_sales_clean.csv") 
        self.log("Step 3: Generating report...")
        results["report"] = self.generate_report()
        if results["report"]:
            files.append("reports/messy_sales_clean_report.csv")
        
        end_time = datetime.now()
        duration = (end_time - start_time).total_seconds()
        
        self.log("=" * 50)
        self.log(f"Pipeline completed in {duration:.2f} seconds")
        self.log("=" * 50)
        
        return {
            "status": "success",
            "duration": duration,
            "results": results,
            "files": files,
            "logs": self.logs
        }


if __name__ == "__main__":
    pipeline = DataPipeline()
    result = pipeline.run()
    print(result)
