"""
DataForge AI - Generated Pipeline
Auto-generated by DataForge Agent
Generated at: 2026-03-21T14:47:51.178037
Operations: ingest, transform, report
"""

import duckdb
import pandas as pd
from datetime import datetime
import os

class DataPipeline:
    """Auto-generated Data Pipeline"""
    
    def __init__(self):
        self.base_path = "/home/z/my-project"
        self.warehouse_path = os.path.join(self.base_path, "warehouse/warehouse.duckdb")
        self.raw_data_path = os.path.join(self.base_path, "data/raw/sales.csv")
        self.clean_data_path = os.path.join(self.base_path, "data/clean/sales_clean.csv")
        self.report_path = os.path.join(self.base_path, "reports/report.csv")
        self.logs = []
    
    def log(self, message):
        """Log a message"""
        timestamp = datetime.now().strftime("%H:%M:%S")
        self.logs.append(f"[{timestamp}] {message}")
        print(message)
    
    def ingest(self):
        """Ingest raw data into DuckDB warehouse"""
        self.log("[Ingest] Reading raw data...")
        
        if not os.path.exists(self.raw_data_path):
            self.log(f"[Ingest] Error: Raw data file not found at {self.raw_data_path}")
            return False
        
        df = pd.read_csv(self.raw_data_path)
        self.log(f"[Ingest] Loaded {len(df)} rows from {self.raw_data_path}")
        
        # Create warehouse directory if needed
        os.makedirs(os.path.dirname(self.warehouse_path), exist_ok=True)
        
        con = duckdb.connect(self.warehouse_path)
        con.execute("CREATE OR REPLACE TABLE sales_raw AS SELECT * FROM df")
        
        # Verify
        count = con.execute("SELECT COUNT(*) FROM sales_raw").fetchone()[0]
        con.close()
        
        self.log(f"[Ingest] Data ingested to warehouse ({count} rows)")
        return True
    def transform(self):
        """Transform and clean data"""
        self.log("[Transform] Cleaning data...")
        
        con = duckdb.connect(self.warehouse_path)
        
        # Clean and transform
        con.execute("""
            CREATE OR REPLACE TABLE sales_clean AS
            SELECT 
                product,
                region,
                CAST(date AS DATE) as date,
                CAST(sales AS DOUBLE) as sales,
                CAST(quantity AS INTEGER) as quantity,
                sales * quantity as total_revenue
            FROM sales_raw
            WHERE product IS NOT NULL 
              AND region IS NOT NULL 
              AND sales > 0
        """)
        
        # Export clean data
        os.makedirs(os.path.dirname(self.clean_data_path), exist_ok=True)
        df = con.execute("SELECT * FROM sales_clean").fetchdf()
        df.to_csv(self.clean_data_path, index=False)
        
        count = len(df)
        con.close()
        
        self.log(f"[Transform] Cleaned {count} rows saved to {self.clean_data_path}")
        return True
    def generate_report(self):
        """Generate summary report"""
        self.log("[Report] Generating report...")
        
        con = duckdb.connect(self.warehouse_path)
        
        # Generate summary report
        report_df = con.execute("""
            SELECT 
                product,
                region,
                COUNT(*) as transaction_count,
                SUM(quantity) as total_quantity,
                SUM(total_revenue) as total_revenue,
                ROUND(AVG(sales), 2) as avg_sales_price
            FROM sales_clean
            GROUP BY product, region
            ORDER BY total_revenue DESC
        """).fetchdf()
        
        os.makedirs(os.path.dirname(self.report_path), exist_ok=True)
        report_df.to_csv(self.report_path, index=False)
        
        count = len(report_df)
        con.close()
        
        self.log(f"[Report] Generated report with {count} rows saved to {self.report_path}")
        return True
    
    def run(self):
        """Execute full pipeline"""
        start_time = datetime.now()
        self.log("=" * 50)
        self.log("DataForge AI Pipeline Execution")
        self.log(f"Started: {start_time}")
        self.log("=" * 50)
        
        results = {}
        files = []
        
        
        self.log("Step 1: Ingesting data...")
        results["ingest"] = self.ingest()
        if results["ingest"]:
            files.append("warehouse/warehouse.duckdb")
        
        self.log("Step 2: Transforming data...")
        results["transform"] = self.transform()
        if results["transform"]:
            files.append("data/clean/sales_clean.csv")
        
        self.log("Step 3: Generating report...")
        results["report"] = self.generate_report()
        if results["report"]:
            files.append("reports/report.csv")
        
        end_time = datetime.now()
        duration = (end_time - start_time).total_seconds()
        
        self.log("=" * 50)
        self.log(f"Pipeline completed in {duration:.2f} seconds")
        self.log("=" * 50)
        
        return {
            "status": "success",
            "duration": duration,
            "results": results,
            "files": files,
            "logs": self.logs
        }


if __name__ == "__main__":
    pipeline = DataPipeline()
    result = pipeline.run()
    print(result)
